name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  commitlint:
    if: github.event_name == 'pull_request'
    uses: madrigal-eschat/ci-workflows/.github/workflows/_commitlint.yml@4f6c6843f3645fc9221822201300088b531534ea # v1.0.0
    with:
      from-sha: ${{ github.event.pull_request.base.sha }}
      to-sha: ${{ github.event.pull_request.head.sha }}

  ci:
    uses: madrigal-eschat/ci-workflows/.github/workflows/_rust-ci.yml@4f6c6843f3645fc9221822201300088b531534ea # v1.0.0

  coverage:
    if: github.event_name == 'pull_request'
    uses: madrigal-eschat/ci-workflows/.github/workflows/_rust-coverage.yml@4f6c6843f3645fc9221822201300088b531534ea # v1.0.0
    with:
      base-ref: ${{ github.base_ref }}

  release:
    if: github.event_name == 'push'
    needs: ci
    permissions:
      contents: write
      issues: write
      pull-requests: write
    uses: madrigal-eschat/ci-workflows/.github/workflows/_semrel.yml@4f6c6843f3645fc9221822201300088b531534ea # v1.0.0
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  release-assets:
    if: needs.release.outputs.released == 'true'
    needs: release
    uses: madrigal-eschat/ci-workflows/.github/workflows/_rust-release-assets.yml@4f6c6843f3645fc9221822201300088b531534ea # v1.0.0
    with:
      binary-name: haptics
      release-tag: ${{ needs.release.outputs.tag }}
    permissions:
      contents: write
